language: node_js

node_js:
  - 0.10
  - 0.12

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  # Install dev. stuff (e.g., selenium drivers).
  - npm run install-dev

env:
  # NOTE: **Cannot** have a space after `:` character in JSON string or else
  # YAML parser will fail to parse correctly.
  global:
    # PhantomJS fails currently. (ROWDY_SETTINGS="local.phantomjs")
    # https://github.com/FormidableLabs/converter-react/issues/34
    - ROWDY_SETTINGS="local.firefox"

script:
  # Run all base checks (with FF browser for functional tests).
  - npm run check-ci

  # Manually send coverage reports to coveralls.
  # - Aggregate client results
  # - Single server and func test results
  - ls  coverage/client/*/lcov.info coverage/server/{rest,unit}/lcov.info coverage/func/lcov.info | cat
  - cat coverage/client/*/lcov.info coverage/server/{rest,unit}/lcov.info coverage/func/lcov.info | ./node_modules/.bin/coveralls || echo "Coveralls upload failed"

  # Prune deps to just production and ensure we can still build
  - npm prune --production
  - npm install --production
  - npm run build
